### ISSUE TITLE
Cleanup tasks

### ISSUE THREAD

**Issue by AlexanderAllen** [AlexanderAllen/panettone#15]
- [x] Unused namespaces on MediaNoche test. DONE #35
- [x] #24
- [x] Decide whether [`typeMatcher2000`](https://github.com/AlexanderAllen/panettone/blob/ee0347d23f2b843c7e5fce475302bd8b5ad54b7a/tests/Unit/MedianocheTest.php#L334) can be combined with [`nativeTypeMatch`](https://github.com/AlexanderAllen/panettone/blob/ee0347d23f2b843c7e5fce475302bd8b5ad54b7a/src/Bread/MediaNoche.php#L1). `typeMatcher2000` is really only used as logging sugar / debug helper and will become outdated as `nativeTypeMatch` evolves. DONE #35
- [x] Collection iteration no longer needs if/else in [`PropertyGenerator`](https://github.com/AlexanderAllen/panettone/blob/ee0347d23f2b843c7e5fce475302bd8b5ad54b7a/tests/Unit/MedianocheTest.php#L435). DONE #35
- [x] Logging capabilities have been muted for code promoted into `src`. Merged in #34
